name: domain_driven_design
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^8.1.3
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  injectable: ^2.4.2
  kt_dart: ^1.1.0
  uuid: ^4.4.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  lint: ^2.3.0

flutter:
  uses-material-design: true
