name: domain_driven_design
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  injectable: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  lint: ^2.3.0

flutter:
  uses-material-design: true
